version: '3.8'

services:
  # ChatGPT UI application
  chatbot-ui:
    container_name: chatbot-ui
    image: ghcr.io/mckaywrigley/chatbot-ui:main
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_HOST=http://azure-openai-proxy:3000
    depends_on:
      - azure-openai-proxy
    networks:
      - vnet
    restart: unless-stopped

  # Azure OpenAI Proxy service
  azure-openai-proxy:
    container_name: azure-openai-proxy
    build:
      context: ../..
    networks:
      - vnet
    restart: unless-stopped

networks:
  vnet:
    driver: bridge